logging:
  level:
    org.springframework.security: INFO

hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 10000

eureka:
  instance:
    prefer-ip-address: true
  client:
    serviceUrl:
      defaultZone: http://codelab-registry:20087/eureka/

security:
  oauth2:
    resource:
      user-info-uri: http://codelab-auth-service:20084/uaa/users/current

spring:
  rabbitmq:
    host: rabbitmq