security:
  oauth2:
    client:
      clientId: codelab-article-service
      clientSecret: ${CODELAB_PASS}
      accessTokenUri: http://codelab-auth-service:20084/uaa/oauth/token
      grant-type: client_credentials
      scope: server

spring:
  data:
    mongodb:
      host: codelab-article-mongodb
      username: user
      password: ${CODELAB_PASS}
      database: codelab
      port: 20183

server:
  context-path: /article
  port: 20083
