spring:
  data:
    mongodb:
      host: codelab-account-mongodb
      username: user
      password: ${CODELAB_PASS}
      database: codelab
      port: 20182
      
server:
  context-path: /account
  port: 20082
