spring:
  data:
    mongodb:
      host: codelab-auth-mongodb
      username: user
      password: ${CODELAB_PASS}
      database: codelab
      port: 20184

server:
  context-path: /uaa
  port: 20084
